version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    links:
      - elasticsearch
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025

  #######################################
  # Elasticsearch
  #######################################
  elasticsearch:
    build:
     context: docker/elasticsearch/
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=elasticsearch.boilerplate.docker
      - VIRTUAL_PORT=9200

volumes:
  elasticsearch:
